permalink: /:year/:month/:day/:title.html
paginate: 10
plugins: [jekyll-paginate]
markdown: kramdown

# 作者信息
author: 
  name: horange
  email: horange@hotmail.com
  link: http://horange.com
  github: http://github.com/horange


# 站点信息
title: horange的博客
description: My personal blog
url: http://horange.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: horange.com

# disqus 设置
disqus:
  shortname: horange

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
